version: "3.8"
services:
  nuxt_dev:
    image: nuxt_dev_image
    container_name: nuxt_dev_container
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - .:/usr/local/app/nuxt
      - /usr/local/app/nuxt/node_modules
    restart: unless-stopped
    networks:
      - nuxt_dev_network

networks:
  nuxt_dev_network:
